version: '3.8'
services:
  web:
    image: realworld-leptos:0.1.0
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/realworld"
      JWT_SECRET: "changeme when deploy to production"
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=realworld
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
