DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Follows;
DROP TABLE IF EXISTS Articles CASCADE;
DROP TABLE IF EXISTS ArticleTags;
DROP TABLE IF EXISTS FavArticles;
DROP TABLE IF EXISTS Comments;
